name: Build QuasarTerm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Build Xcode archive
        run: |
          xcodebuild \
            -scheme "QuasarTerm" \
            -archivePath $RUNNER_TEMP/QuasarTerm.xcarchive \
            -destination platform=macOS \
            -allowProvisioningUpdates \
            clean archive
      - name: Export app
        env:
          EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
        run: |
          EXPORT_OPTS_PATH=./ExportOptions.plist
          xcodebuild -exportArchive -archivePath $RUNNER_TEMP/winston.xcarchive -exportOptionsPlist $EXPORT_OPTS_PATH -exportPath $RUNNER_TEMP/build
     
      - name: Upload to Github Releases
        uses: actions/upload-artifact@v3
        with:
          name: QuasarTerm
          path: ${{ runner.temp }}/build/QuasarTerm.app
