name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos-build:
    runs-on: macos-14

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Build (macOS)
      uses: SwiftActions/SwiftBuild@0.2
      with:
        target: "QuasarTerm"
        product: "QuasarTerm"
        verbose: true
