name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos-build:
    runs-on: macos-12

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Build (macOS)
      uses: SwiftActions/SwiftBuild@0.2
    - name: Run tests
      uses: SwiftActions/SwiftTest@0.2
